### ISSUE TITLE
help wanted with trying to setup a wrapper function for encrypting/decrypting const char* values

### ISSUE THREAD

**Issue by VaasKahnGrim** [kokke/tiny-AES-c#158] opened 2020-03-07 01:30 UTC
I'm trying to setup a wrapper function to make it easier to use this library in a project of mine but I'm sorta running into 2 main issues.

Issue 1 is I can't seem to find a way of converting a const char* into a uint8_t array.

Issue 2 is that I can't seem to figure out what the decrypt/encrypt functions output in order to store it in the output variable so that I can return a decrypted const char* value to the rest of my project.

This is the current wrapper function I have, any way I can get these 2 issues fixed?

```c++
static const char* crypt_wrapper(int mode,const char* key,const char* string){
	//int mode - should we decrypt or encrypt the string?
	//const char* - the key used for decrypting/encrypting the string
	//const char* - the string we want to decrypt/encrypt

	const char* output;
	uint8_t formated_key[1] = {};
	uint8_t formated_string[1] = {};

	struct AES_ctx ctx;
	AES_init_ctx(&ctx,formated_key);

	if(mode == 1){
		output = AES_CBC_encrypt_buffer(&ctx, formated_string, sizeof(formated_string));
	}else{
		output = AES_CBC_decrypt_buffer(&ctx, formated_string, sizeof(formated_string));
	}
	return output; // the string we return after encrypting/decrypting it
}
```

**Comment by kokke** [comment] 2020-03-07 02:09
Hi @VaasKahnGrim 

1) uint8_t is usually a typedef for unsigne char. Your const char* points to an array of chars -> the conversion should be a matter of casting.

2) I quote from the readme: "No padding is provided so for CBC and ECB all buffers should be multiples of 16 bytes.". Your key and strings are not multiples of 16 bytes -> they are only 1 byte.

I will close this issue since it's not a bug in this library. This question is better suited for a Q&A-site like stackoverflow.com or something similar

**Closed by kokke** 2020-03-07 02:09 UTC

**Comment by VaasKahnGrim** [comment] 2020-03-07 02:42
if I have to keep the string and the key in a multiple of 16 do you have any recommendations for dealing with much larger amounts of data being encrypted/decrypted? say 10mb worth in size for a string?

trying to basically encrypt data being opened from files here but its sounding like tiny-aes-c won't even be able to fill that role here

**Comment by kokke** [comment] 2020-03-07 10:10
You can encrypt or decrypt an arbitrary amount of data, but you need to work on a multiple of 16 bytes at a time. 

Again, this question is much more suited for stackoverflow.com
