### ISSUE TITLE
Hellp me!

### ISSUE THREAD

**Issue by haydoiday228** [kokke/tiny-AES-c#140] opened 2019-06-11 06:27 UTC
Why it only create  16 bytes result? I use encrypt_ecb with:
+ key: uint8_t key[] = { '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1' };
+ in: uint8_t in[]  = { '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',  };

in web
https://www.devglan.com/online-tools/aes-encryption-decryption
the result 32 bytes: AD0110483D0559D12E8CB97203E6C908F30C69C4F945E654EBD4B388B1C8F790

**Comment by kokke** [comment] 2019-06-14 10:50
Hi @haydoiday228 

ECB works in 128 bit / 16 byte blocks, so if you want to use this mode with larger inputs, you need to handle chunking and padding etc. yourself. There are examples of how to do that in `test.c`.

I don't recommend you use this library unless you have a good idea of how AES and the different modes of operations work. 

Please understand the differences between binary, ASCII encoded and BASE64 encoded data - which is often the cause of confusion, when users ask me "why does the library give a different output from this web page".

ECB is generally not recommended, unless you "know what you are doing". See https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_Codebook_(ECB)

I will close this issue, because it is a usage error, not a bug in the library.

**Closed by kokke** 2019-06-14 10:50 UTC
