### ISSUE TITLE
decrypt and encry wrong

### ISSUE THREAD

**Issue by txy0110** [kokke/tiny-AES-c#149] opened 2019-09-11 13:29 UTC
I try uint8_t in[16] = {0x6D, 0x6F, 0x64, 0x65, 0x2E, 0x0D, 0x0D, 0x0A, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},first I encry it, then decrypt,result is {0x6D, 0x6F, 0x64, 0x65, 0x2E, 0x0D, 0x0D, 0x0D, 0x0A, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, result length is 17;There are many other similar cases

**Comment by kokke** [comment] 2019-09-27 12:36
I'm closing this issue as it seems to rely in a misunderstanding. 

I will of course reopen if code demonstrating the problem is posted.

**Closed by kokke** 2019-09-27 12:36 UTC
