### ISSUE TITLE
CBC mode AES 256, First Block wont decry pt  properly

### ISSUE THREAD

**Issue by Sujaydas** [kokke/tiny-AES-c#132] opened 2019-04-08 19:59 UTC
I am using the AES 256 CBC mode decryption , its seems the results of decrpytion  are not similar to original bytes, I am using IOpenSSL to encrypt the data. There is no padding during the openSSL,

**Comment by kokke** [comment] 2019-04-23 12:09
Hi @Sujaydas 

As mentioned in the readme on the front page, this library is verified against the NIST standard vectors, which gives assurance that at least the simplest modes of operation are working correctly.
The library is also used in quite a few commercial products and gets a lot of hobbyist use as well.

I am certain that your issue stems from incorrect usage or unmatched assumptions somewhere, e.g. related to padding. 

Since I cannot help you debug your issue with that tiny amount of information you've given, I'm closing for irrelevancy (it's a usage problem, not a bug in the code).

**Closed by kokke** 2019-04-23 12:09 UTC
