### ISSUE TITLE
AES_CBC_encrypt_buffer incorrect

### ISSUE THREAD

**Issue by crashan** [kokke/tiny-AES-c#133] opened 2019-04-21 11:46 UTC
my code:
```c++
uint8_t input[16];
memcpy(input, "qwertyuiopasdfg", 16);
uint8_t* key = (uint8_t*)"abcdefghijklmnop";
uint8_t* iv = (uint8_t*)"1234567890123456";

AES_ctx ctx;
AES_init_ctx(&ctx, key);
AES_ctx_set_iv(&ctx, iv);
AES_CBC_encrypt_buffer(&ctx, input, 16);
std::string b64str = base64_encode(input, 16);
```
my config
```c++
#define AES128 1
```
After `AES_CBC_encrypt_buffer`, base64 string of cipher text is `Xb7krmkZUab+/NMTt61wNA==`, but the base64 string of the correct cipher is `i0pUSztmi/SMeLmvoqG4iw==` actually.
But, if i pass the raw cipher to `AES_CBC_decrypt_buffer`, i will get the correct plain text:
```c++
// ...
AES_ctx_set_iv(&ctx, iv);
AES_CBC_encrypt_buffer(&ctx, input, 16);
// ...
AES_ctx_set_iv(&context, iv); // reset iv
AES_CBC_decrypt_buffer(&context, input, 16); // input = "qwertyuiopasdfg"
```

**Comment by kokke** [comment] 2019-04-23 08:00
Hi @crashan 

>But, if i pass the raw cipher to AES_CBC_decrypt_buffer, i will get the correct plain text:

Sounds like your problem is with the base64 handling part of the code, not the AES code.

This part of your code looks suspicious to me, and I have added two comments.

```C
AES_ctx ctx;
AES_init_ctx(&ctx, key);
AES_ctx_set_iv(&ctx, iv);
AES_CBC_encrypt_buffer(&ctx, input, 16); // after encryption, the buffer is no longer null-terminated
std::string b64str = base64_encode(input, 16); // does this function expect a null-terminated string?
```

**Comment by crashan** [comment] 2019-04-23 13:34
Hi @kokke 
```c++
// this function encodes 16 bytes of the input, and not need a null-terminated string
// you can find it's implement [here](https://github.com/ReneNyffenegger/cpp-base64/blob/master/base64.cpp)
std::string b64str = base64_encode(input, 16);
```
I try to print the buffer with hex format after encryption, it's `5DBEE4AE691951A6FEFCD313B7AD7034`.
But the correct hex string is `8B4A544B3B668BF48C78B9AFA2A1B88B`.

**Comment by kokke** [comment] 2019-04-23 15:02
Hi @crashan 

I don't understand what you mean by this part:

> I try to print the buffer with hex format after encryption, it's 5DBEE4AE691951A6FEFCD313B7AD7034.
> But the correct hex string is 8B4A544B3B668BF48C78B9AFA2A1B88B.


From this snippet of your first post:
> But, if i pass the raw cipher to AES_CBC_decrypt_buffer, i will get the correct plain text:

... I got the impression that decryption worked if you skipped encoding to/decoding from base64.

If decryption works with the raw output from AES_CBC_encrypt, the problem is not with the AES library.

**Comment by crashan** [comment] 2019-04-23 16:09
```c++
// this is my test
uint8_t input[16];
memcpy(input, "qwertyuiopasdfg", 16);
uint8_t* key = (uint8_t*)"abcdefghijklmnop";
uint8_t* iv = (uint8_t*)"1234567890123456";

AES_ctx ctx;
AES_init_ctx(&ctx, key);
AES_ctx_set_iv(&ctx, iv);
AES_CBC_encrypt_buffer(&ctx, input, 16);

// print raw cipher with hex format, and got 5DBEE4AE691951A6FEFCD313B7AD7034
for (int i = 0; i < 16; ++i)
    printf("%X", input[i]);
```
I use a online tool for aes encryption with same params, and got 8B4A544B3B668BF48C78B9AFA2A1B88B
```
plain text: qwertyuiopasdfg
mode:      cbc
key size:   128bits
iv:             1234567890123456
key:          abcdefghijklmnop
```

**Comment by kokke** [comment] 2019-04-23 18:20
Hi @crashan 

You are comparing apples to oranges. The AES implementation encrypts a 16-byte message, consisting of 15 characters and an implicit null-termination.
The online JS implementation encrypts a 15 byte message, so the result differs.

Comparing this library with Python's implementation, yields the same output: 5DBEE4AE691951A6FEFCD313B7AD7034

```Python
from Crypto.Cipher import AES
msg = "qwertyuiopasdfg\0"
iv  = "1234567890123456"
key = "abcdefghijklmnop"
cipher = AES.new(key, AES.MODE_CBC, iv)
output = cipher.encrypt(msg)
print("".join(["%.02X" % ord(o) for o in output]))
# 5DBEE4AE691951A6FEFCD313B7AD7034
```

**Comment by kokke** [comment] 2019-04-23 18:21
Closing as this is obviously a usage issue.

**Closed by kokke** 2019-04-23 18:21 UTC

**Comment by kokke** [comment] 2019-04-23 19:20
The online tool uses PKCS5 padding, so instead of encrypting "qwertyuiopasdfg\0" I believe it's encrypting "qwertyuiopasdfg\1"
