### ISSUE TITLE
AES128-CBC does not correctly working with STM device (NUCLE0-F401RE)

### ISSUE THREAD

**Issue by ZioMorgan** [kokke/tiny-AES-c#178] opened 2020-10-24 14:31 UTC
I've tried the code with my Nucleo device, AES onn ECB works correctly, but with AES on CBC mode, i noticed that the encryption process is correct just for a piece of the plain text, the rest is incorrect. 
I compared the resulting cipher text with the one generated by an online AES cipher. 
The used key and plain-text are the ones contained into the aes.c file

**Comment by sburgh01** [comment] 2020-12-18 08:25
I tested with the test.c File on a STM32F373. Everything workes fine here.

Because CBC is not tested with multipe calls i Editted Line 215
from:
`AES_CBC_encrypt_buffer(&ctx, in, 64);`
to
`    
AES_CBC_encrypt_buffer(&ctx, in, 32);
AES_CBC_encrypt_buffer(&ctx, in+32, 32);
`
To enable some cbc chaining in the algorithm.
Everything works fine.

**Comment by kokke** [comment] 2021-01-05 20:30
Hi @ZioMorgan 

I have had no problems with this code on various STM32 MCUs and lots of other architectures.
CBC involves an IV which is a common source of usage problems. I suggest you ensure that you are encrypting and decrypting with the same key + IV pairs.

Please post the code used or a minimally reproducible example of your problem.

**Comment by kokke** [comment] 2021-01-06 01:40
Closing temporarily until OP replies

**Closed by kokke** 2021-01-06 01:40 UTC
